run_name: "bcastor/run"
parallel: False
n_workers: 4
initial_dataset:
  generate: True,
  n_points: 20
checkpoint:
  name: "checkpoint"
  n_step_save: 1
total_iterations: 20
resolution:
  value: 0.002
  constant_resolution: False
  r_decay_steps: 30
  initial: 1e-2
  final: 1e-3
batch_sampling:
  tpe_trials: 200
  rank_samples: 5
  alpha: 2
eci:
  num_samples: 128 # Fixed samples
