num_inputs: 2
num_outputs: 2
num_samples: 100
checkpoint:
  n_step_save: 500
  name: chckpnt
run_name: mlscan/run
total_iterations: 10
parallel: False
n_workers: 4
initial_dataset:
  generate: True,
  n_points: 10
